sol_p1 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/1_sol_reto1.csv", sep = ",")
sol_p2 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/2_sol_reto1.csv", sep = ",")
sol_p3 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/3_sol_reto1.csv", sep = ",")
sol_p4 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/4_sol_reto1.csv", sep = ",")
sol_p5 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/5_sol_reto1.csv", sep = ",")
sol_p6 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/6_sol_reto1.csv", sep = ",")
sol_p7 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/7_sol_reto1.csv", sep = ",")
sol_p8 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/8_sol_reto1.csv", sep = ",")
sol_p9 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/9_sol_reto1.csv", sep = ",")
sol_p10 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/10_sol_reto1.csv", sep = ",")
sol_p11 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/11_sol_reto1.csv", sep = ",")
sol_p12 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/12_sol_reto1.csv", sep = ",")
sol_p13 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/13_sol_reto1.csv", sep = ",")
sol_p14 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/14_sol_reto1.csv", sep = ",")
sol_p15 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/15_sol_reto1.csv", sep = ",")
sol_p16 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/16_sol_reto1.csv", sep = ",")
sol_p17 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/17_sol_reto1.csv", sep = ",")
sol_p18 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/18_sol_reto1.csv", sep = ",")
sol_p19 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/19_sol_reto1.csv", sep = ",")
sol_p20 <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/20_sol_reto1.csv", sep = ",")

sol_p1_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/1_sol_reto1_s.csv", sep = ",")
sol_p2_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/2_sol_reto1_s.csv", sep = ",")
sol_p3_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/3_sol_reto1_s.csv", sep = ",")
sol_p4_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/4_sol_reto1_s.csv", sep = ",")
sol_p5_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/5_sol_reto1_s.csv", sep = ",")
sol_p6_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/6_sol_reto1_s.csv", sep = ",")
sol_p7_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/7_sol_reto1_s.csv", sep = ",")
sol_p8_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/8_sol_reto1_s.csv", sep = ",")
sol_p9_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/9_sol_reto1_s.csv", sep = ",")
sol_p10_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/10_sol_reto1_s.csv", sep = ",")
sol_p11_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/11_sol_reto1_s.csv", sep = ",")
sol_p12_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/12_sol_reto1_s.csv", sep = ",")
sol_p13_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/13_sol_reto1_s.csv", sep = ",")
sol_p14_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/14_sol_reto1_s.csv", sep = ",")
sol_p15_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/15_sol_reto1_s.csv", sep = ",")
sol_p16_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/16_sol_reto1_s.csv", sep = ",")
sol_p17_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/17_sol_reto1_s.csv", sep = ",")
sol_p18_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/18_sol_reto1_s.csv", sep = ",")
sol_p19_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/19_sol_reto1_s.csv", sep = ",")
sol_p20_s <- read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/20_sol_reto1_s.csv", sep = ",")

optimos_p <-read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/opt_reto1.csv", sep = ",")
optimos_s <-read.csv("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/opt_reto1_s.csv", sep = ",")

mejor1 <- max(sol_p1)
mejor2 <- max(sol_p2)
mejor3 <- max(sol_p3)
mejor4 <- max(sol_p4)
mejor5 <- max(sol_p5)
mejor6 <- max(sol_p6)
mejor7 <- max(sol_p7)
mejor8 <- max(sol_p8)
mejor9 <- max(sol_p9)
mejor10 <- max(sol_p10)
mejor11 <- max(sol_p11)
mejor12 <- max(sol_p12)
mejor13 <- max(sol_p13)
mejor14 <- max(sol_p14)
mejor15 <- max(sol_p15)
mejor16 <- max(sol_p16)
mejor17 <- max(sol_p17)
mejor18 <- max(sol_p18)
mejor19 <- max(sol_p19)
mejor20 <- max(sol_p20)

mejor1_s <- max(sol_p1_s)
mejor2_s <- max(sol_p2_s)
mejor3_s <- max(sol_p3_s)
mejor4_s <- max(sol_p4_s)
mejor5_s <- max(sol_p5_s)
mejor6_s <- max(sol_p6_s)
mejor7_s <- max(sol_p7_s)
mejor8_s <- max(sol_p8_s)
mejor9_s <- max(sol_p9_s)
mejor10_s <- max(sol_p10_s)
mejor11_s <- max(sol_p11_s)
mejor12_s <- max(sol_p12_s)
mejor13_s <- max(sol_p13_s)
mejor14_s <- max(sol_p14_s)
mejor15_s <- max(sol_p15_s)
mejor16_s <- max(sol_p16_s)
mejor17_s <- max(sol_p17_s)
mejor18_s <- max(sol_p18_s)
mejor19_s <- max(sol_p19_s)
mejor20_s <- max(sol_p20_s)

mejores_p <- c(mejor1,mejor2,mejor3,mejor4,mejor5,mejor6,mejor7,mejor8,mejor9,mejor10,mejor11,mejor12,
               mejor13,mejor14,mejor15,mejor16,mejor17,mejor18,mejor19,mejor20)

mejores_s <- c(mejor1_s,mejor2_s,mejor3_s,mejor4_s,mejor5_s,mejor6_s,mejor7_s,mejor8_s,mejor9_s,mejor10_s,mejor11_s,mejor12_s,
               mejor13_s,mejor14_s,mejor15_s,mejor16_s,mejor17_s,mejor18_s,mejor19_s,mejor20_s)


qqnorm(mejores_p);qqline(mejores_p)
shapiro.test(mejores_p)
qqnorm(mejores_s);qqline(mejores_s)
shapiro.test(mejores_s)
plot(density(mejores_s))

test <- t.test(mejores_p,mejores_s)
print(test)

boxplot(mejores_p,mejores_s,names=c("Ruleta","Aleatorio"))
medias <- c(mean(mejores_p),mean(mejores_s))
points(medias,pch=18,col="red")

gap_p <- data.frame()
gap_s <- data.frame()
for(n in 1:20){
  gap_p <- rbind(gap_p,(optimos_p$X9424.2098664102[n] - mejores_p[n]) / optimos_p$X9424.2098664102[n])
  gap_s <- rbind(gap_s,(optimos_s$X10981.7127514566[n] - mejores_s[n]) / optimos_s$X10981.7127514566[n])
}

png("/home/pabloide/Documentos/3 Semestre/R_paralelo/p10/reto1/gap.png")
plot(1:20, gap_p$X0.0724497142539675, xlab="Iteraciones", ylab="GAP", type='l', ylim = c(0,.12))
points(1:20, gap_p$X0.0724497142539675, pch=15)
lines(1:20, gap_s$X0.0329211633893582, xlab="", ylab="GAP", type='l', col="red")
points(1:20, gap_s$X0.0329211633893582, pch=12)
legend("topleft", c("Ruleta","Aleatorio"), pch = c(15,12), inset = .02)
graphics.off()
